# Copyright 2023 The Protobom Authors
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to write releases

    steps:
      - name: Install publish-release
        uses: puerco/release-actions/setup-publish-release@ef6d340ddd115f41dc26c18893b41d9c79cdc7d2 # main

      - name: Publish Release
        uses: puerco/release-actions/publish-release@ef6d340ddd115f41dc26c18893b41d9c79cdc7d2 # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        